name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install prerequisites
      run: sudo apt install -y nasm gcc binutils grub-common make gcc-multilib libc6-dev-i386 mtools

    - name: Run make build
      run: make build
