name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install prerequisites
      run: sudo apt install -y nasm gcc ld grub-common make 

    - name: Run make build
      run: make build
